### ISSUE TITLE
Update mempool v2.1.2 & fixes

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#2076]
This issue is based on the following sub issues:

- [x] merge update & fix #2014
- [x] drop database fix #1960
- [x] default mempool back to 300MB #2007 #2008

**Comment by rootzoll** [comment]
All merged in preparation of v1.7 .. set for final testing

**Comment by rootzoll** [comment]
Testing looks good. Closing for v.17 release.
