### ISSUE TITLE
[v1.11.0 RELEASE] Checklist

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#4525]
Getting closer to final release - check list:
- [x] PR dev fixes
- [x] build signed final images (update rc7 builds)
- [x] upload final images
- [x] short internal team tests
- [x] create & seed torrents
- [x] link final images http+torrent
- [x] set main branch to `dev`
- [x] announce TG & twitter

**Comment by cstenglein** [comment]
- [ ] set main branch to `dev`

**Comment by rootzoll** [comment]
Its done :D  https://twitter.com/rootzoll/status/1780717131908186157
